<div class="container fieldset-wrapper" ng:controller="controller" id='ng-controller' 
    style="margin-left:20px;margin-top: 0" sync-ko from='products' to='angularjs_swap_data_1'>
    <div class="row header">
        <div class="col-md-2">Product ID</div>
        <div class="col-md-4">Product Sku</div>
        <div class="col-md-12">Product Name</div>
        <div class="col-md-2">Qty</div>
        <div class="col-md-2">Price($)</div>
        <div class="col-md-2">Action</div>
    </div>
    <div class="row" ng-repeat="product in products | filter : {'is_delete' : false} | orderBy:'simple_product_id'" ng-class="$index % 2 == 0 ? 'even-row' : 'odd-row'">
        <div class="col-md-2">{{product.simple_product_id}}</div>
        <div class="col-md-4">{{product.simple_product_sku}}</div>
        <div class="col-md-12">{{product.simple_product_name}}</div>
        <div class="col-md-2"><input ng-model="product.simple_product_quantity"/></div>
        <div class="col-md-2">{{product.price}} * {{product.simple_product_quantity}} = {{product.price * product.simple_product_quantity}}</div>
        <div class="col-md-2">
            <button ng-click="delProduct(product.simple_product_sku)" 
                class="btn btn-small btn-info" 
                style="width:100%;">Delete
            </button>
        </div>
    </div>

    <div class="row">
        <button ng-click="openModal('<?= $block->getViewFileUrl('Yong_Angularjs::angular-modal/addsimpleproduct.html')?>', 
            '<?php echo $this->getUrl('mui/index/render')?>?isAjax=true',
            products,
            {'paging':{'current':1, 'pageSize':20},
            'filters':{'placeholder':1, 'status':1},
            'sorting':{'direction':'desc', 'field':'entity_id'},
            'form_key':'<?php echo $this->getFormKey()?>','namespace':'bundle_product_listing'})" class="btn btn-small btn-success">
            Add New Simple Product
        </button>
    </div>
    <div style="display:none" ng-init='initProducts()'></div>
</div>
<script>
require(
    [
        'jquery',
        'ko',
        'angular',
        'ngstorage',
        'angularBootstrap',
        'modalScript',
        'syncKo',
        'mymodalService',
        'mytabController'
    ],
    function ($,
        ko,
        angular,
        ngStorage, 
        uiBootstrap,
        modalScript,
        syncKo,
        mymodalService,
        mytabController) {
        "use strict";

        angular.module('mytab', ['ui.bootstrap', 'ngStorage'])
            .directive('modalScript', modalScript)
            .directive('syncKo', syncKo)
            .service('mymodalService', ['$uibModal', mymodalService])
            .controller('controller', mytabController);
        angular.bootstrap(document, ['mytab']);
    });
</script>